config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  devise_for :users
  resources :reservations
  resources :stays, only: %i[ index new show edit create update ]

  put "stays/:id/enable", to: "stays#enable", as: "enable_stay"
  put "stays/:id/disable", to: "stays#disable", as: "disable_stay"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "reservations/:id/receipt", to: "generate_receipts#generate_pdf", as: "generate_receipt"
  get "contact", to: "homepage#contact", as: "contact"
  # Defines the root path route ("/")
  root "homepage#index"
end

app/models/stay.rb
class Stay < ApplicationRecord
  has_rich_text :description

  has_many :reservations

  validates :name, :address, :description, :max_persons, :bedrooms, :bathrooms, :area, :price, presence: true

  validates :pet_friendly, inclusion: { in: [true, false] }

  validates :name, uniqueness: true

  validates :image_url, allow_blank: true, format: {
                          with: %r{\.(gif|png|jpe?g|)\z}i,
                          message: "must be an URL for JPG, GIF or PNG",
                        }

  validates :price, :area, numericality: { greater_than_or_equal_to: 0.01 }

  validates :max_persons, :bedrooms, :bathrooms, numericality: {
                                                   only_integer: true,
                                                   greater_than_or_equal_to: 1,
                                                 }

  scope :enabled, -> { where(enabled: true) }
  scope :disabled, -> { where(enabled: false) }
end

app/controllers/stays_controller.rb
class StaysController < ApplicationController
  before_action :set_stay, only: %i[ show edit update enable disable ]
  before_action :authenticate_user!, only: %i[ new edit create update enable disable ]

  # GET /stays or /stays.json
  def index
    if params[:check_in] && params[:check_out] && !params[:check_in].strip.empty? && !params[:check_in].strip.empty?
      begin
        start_date = params[:check_in].to_date
        end_date = params[:check_out].to_date
      rescue Date::Error
        redirect_to root_path, notice: "Invalid dates provided, please try again"
        return
      else
        if !start_date || !end_date
          redirect_to root_path, notice: "Please provide both check in and check out dates"
          return
        end

        if end_date < start_date
          redirect_to root_path, notice: "Check in cannot be after check out, please try again"
          return
        else
          get_available_stays(start_date, end_date)
        end
      end
    else
      if user_signed_in?
        @stays = Stay.all.order(:enabled)
      else
        @stays = Stay.enabled
        flash[:notice] = "Dates not supplied. Showing all stays."
      end
    end
    @pagy, @stays = pagy(@stays)
  end

  # GET /stays/1 or /stays/1.json
  def show
  end

  # GET /stays/new
  def new
    @stay = Stay.new
  end

  # GET /stays/1/edit
  def edit
  end

  # POST /stays or /stays.json
  def create
    @stay = Stay.new(stay_params)

    respond_to do |format|
      if @stay.save
        format.html { redirect_to stay_url(@stay), notice: "Stay was successfully created." }
        format.json { render :show, status: :created, location: @stay }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stays/1 or /stays/1.json
  def update
    respond_to do |format|
      if @stay.update(stay_params)
        format.html { redirect_to stay_url(@stay), notice: "Stay was successfully updated." }
        format.json { render :show, status: :ok, location: @stay }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stays/1 or /stays/1.json
  def disable
    @stay.enabled = false

    respond_to do |format|
      if @stay.save!
        format.html { redirect_to stay_url(@stay), notice: "Stay was successfully disabled." }
        format.json { render :show, status: :ok, location: @stay }
      else
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @stay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stays/1 or /stays/1.json
  def enable
    @stay.enabled = true
    respond_to do |format|
      if @stay.save!
        format.html { redirect_to stay_url(@stay), notice: "Stay was successfully enabled." }
        format.json { render :show, status: :ok, location: @stay }
      else
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @stay.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_stay
    @stay = Stay.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  # Only allow a list of trusted parameters through.
  def stay_params
    params.require(:stay).permit(:name, :address, :description, :image_url, :max_persons, :pet_friendly, :bedrooms, :bathrooms, :area, :price)
  end

  def get_available_stays(start_date, end_date)
    reserved_stays = Reservation.where(check_in: start_date..(end_date-1))
      .or(Reservation.where(check_out: (start_date+1)..end_date))
      .or(
        (Reservation.where(check_out: end_date..)
        .and(Reservation.where(check_in: ..start_date)))
      )
    reserved_stays = reserved_stays.map { |rs| rs.stay_id }
    @stays = Stay.where.not(id: reserved_stays).enabled
  end
end

app/helpers/stays_helper.rb
module StaysHelper
end

app/views/stays/_form.html.erb
<%= form_with(model: stay, class: "contents") do |form| %>
  <% if stay.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(stay.errors.count, "error") %> prohibited this stay from being saved:</h2>

      <ul>
        <% stay.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="my-5">
    <%= form.label :address, class: "form-label" %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="my-5">
    <%= form.label :image_url, class: "form-label" %>
    <%= form.text_field :image_url, class: "form-control" %>
  </div>

  <div class="my-5">
    <%= form.label :description, class: "form-label" %>
    <%= form.rich_text_area :description, class: "form-control" %>
  </div>

  <div class="my-5">
    <%= form.label :max_persons, class: "form-label" %>
    <%= form.number_field :max_persons, class: "form-control" %>
  </div>

  <div class="my-5">
    <%= form.label :pet_friendly, class: "form-label" %>
    <%= form.check_box :pet_friendly, class: "form-control" %>
  </div>

  <div class="my-5">
    <%= form.label :bedrooms, class: "form-label" %>
    <%= form.number_field :bedrooms, class: "form-control" %>
  </div>

  <div class="my-5">
    <%= form.label :bathrooms, class: "form-label" %>
    <%= form.number_field :bathrooms, class: "form-control" %>
  </div>

  <div class="my-5">
    <%= form.label :area, class: "form-label" %>
    <%= form.text_field :area, class: "form-control" %>
  </div>

  <div class="my-5">
    <%= form.label :price, class: "form-label" %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/stays/_stay.html.erb
<div id="<%= dom_id stay %>">
  <h1 class="text-center"> <%= stay.name %> </h1>
  <% if !stay.enabled %>
    <h5 class="note note-danger mb-3 text-center"> <%= user_signed_in? ? "This stay is disabled. This will prevent the stay from showing up in search results." : "This stay is curently not taking reservations." %> </h5>
  <% end %>
    <%= image_tag stay.image_url, class: "img-fluid h-50" %>

  <p class="my-5">
    <b class="font-medium mb-1"> Address: </b> <i class="font-medium mb-1"> <%= stay.address %></i>
  </p>

  <div class="grid">

      <p class="my-5">
        <%= stay.description %>
      </p>


    <div class="md:w-2/4 text-right place-items-center">
      <table class="table">
        <tr>
          <td>
            <b class="font-medium mb-1">Max persons: </b>
          </td>
          <td>
            <%= stay.max_persons %>
          </td>
        </tr>

        <tr>
          <td>
            <b class="font-medium mb-1">Pet friendly: </b>
          </td>
          <td>
            <p class="my-2"> <%= stay.pet_friendly ? "Yes" : "No" %> </p>
          </td>
        </tr>

        <tr>
          <td>
              <b class="font-medium mb-1">Bedrooms: </b>
          </td>
          <td>
            <p class="my-2"> <%= stay.bedrooms %> </p>
          </td>
        </tr>

        <tr>
          <td>
              <b class="font-medium mb-1">Bathrooms: </b>
          </td>
          <td>
            <p class="my-2"> <%= stay.bathrooms %> </p>
          </td>
        </tr>

        <tr>
          <td>
              <b class="font-medium mb-1">Area: </b>
          </td>
          <td>
            <p class="my-2"> <%= stay.area %> </p>
          </td>
        </tr>

        <tr>
          <td>
              <strong class="font-medium mb-1">Price per night:</strong>
          </td>
          <td>
            <p class="my-2"> <b> <%= number_to_currency(stay.price, :unit => "€", :separator => ",", :delimiter => ".") %> </p> </b>
          </td>
        </tr>
      </table>

    </div>
  </div>
</div>

app/views/stays/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing stay</h1>

  <%= render "form", stay: @stay %>

  <%= link_to "Show this stay", @stay, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to stays", stays_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/stays/index.html.erb
<div class="w-100">
  <% if notice.present? %>
    <p class="py-2 px-3 note note-success text-green-500 font-medium rounded-lg inline-block " id="notice"><%= notice %></p>
  <% end %>
  <% content_for :title, "Available vacation homes" %>
  <div class="d-flex flex-column justify-content-around align-items-center pb-8">
    <h3 class="mx-auto font-bold text-4xl">There are <%= "#{@pagy.count} #{"stay".pluralize(@pagy.count)}" %> to choose from</h3>
    <br/>
    <% if @pagy.count > @pagy.items %>
      <div class="my-16">
        <%== pagy_nav(@pagy) %>
      </div>
    <% end %>
    <br/>
    <% if user_signed_in? %>
      <div class="mt-8">
        <%= link_to "Add a new stay", new_stay_path, class: "btn btn-primary" %>
      </div>
    <% end %>
    <br/>
    <% @stays.each do |stay| %>
      <div class="d-flex flex-row">
        <%= link_to image_tag(stay.image_url, class: "img-fluid p-2"), stay_path(stay, check_in: params[:check_in], check_out: params[:check_out]), class: "w-50" %>
        <div class="card">
          <div class="card-body p-2">
            <h5 class="card-title"> <%= link_to stay.name, stay_path(stay, check_in: params[:check_in], check_out: params[:check_out]), class: "hover:underline" %></h5>
            <p class="card-text"> <b>Address:</b> <%= stay.address %> </p>
            <p class="card-text"> <%= truncate(strip_tags(stay.description), length: 140) %> </p>
            <% if !stay.enabled? %>
              <p class="card-text"> <b>Disabled</b></p>
            <% end %>
            <p class="card-text"> <%= truncate(strip_tags(stay.description), length: 140) %> </p>
            <div class="d-flex flex-row justify-content-between pb-8">
              <p class="card-text"> <b><%= number_to_currency(stay.price, :unit => "€", :separator => ",", :delimiter => ".") %></b> per night </p>
              <%= link_to "Show this stay", stay_path(stay, check_in: params[:check_in], check_out: params[:check_out]), class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
      <br/>
    <% end %>
    <br/>
    <% if @pagy.count > @pagy.items %>
      <%== pagy_nav(@pagy) %>
    </div>
  <% end %>
</div>

app/views/stays/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New stay</h1>

  <%= render "form", stay: @stay %>
  <br/>
  <%= link_to "Back to stays", stays_path, class: "btn btn-secondary" %>
</div>

app/views/stays/show.html.erb
<div class="w-100 d-flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 note note-success text-green-500 font-medium rounded-lg inline-block " id="notice"><%= notice %></p>
    <% end %>
    <%= render @stay %>
    <br/>
    <div class="d-flex justify-content-around gap-10" style="width: 100%">
      <% if @stay.enabled? %>
        <%= link_to "Book this stay", new_reservation_path(stay_id: @stay.id, check_in: params[:check_in], check_out: params[:check_out]), 
          class: "btn btn-primary" %>
      <% end %>
      <% if user_signed_in? %>
        <%= link_to "Edit this stay", edit_stay_path(@stay), class: "btn btn-primary" %>
        <%= button_to "#{@stay.enabled? ? "Disable" : "Enable" } this stay", @stay.enabled? ? disable_stay_path(@stay) : enable_stay_path(@stay) , method: :put, class: "btn btn-primary" %>
      <% end %>
      <%= link_to "Back to all stays", stays_path, class: "btn btn-secondary" %>
    </div>
    <br/>
  </div>
</div>