config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  devise_for :users
  resources :reservations
  resources :stays, only: %i[ index new show edit create update ]

  put "stays/:id/enable", to: "stays#enable", as: "enable_stay"
  put "stays/:id/disable", to: "stays#disable", as: "disable_stay"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "reservations/:id/receipt", to: "generate_receipts#generate_pdf", as: "generate_receipt"
  get "contact", to: "homepage#contact", as: "contact"
  # Defines the root path route ("/")
  root "homepage#index"
end

app/models/reservation.rb
require "paygo"

class Reservation < ApplicationRecord
  enum pay_type: {
    "iDeal" => 0,
    "Bank Card" => 1,
    "Pay at stay" => 2,
  }

  enum status: {
    "Booked - Payment pending" => 0,
    "Booked - Paid" => 1,
    "Checked in" => 2,
    "Checked out" => 3,
    "Cancelled" => 4
  }

  belongs_to :stay

  validates :name, :address, :email, :check_in, :check_out, presence: true
  validates :pay_type, inclusion: pay_types.keys
  validates :check_in, :check_out, availability: true, on: :create
  validate :check_out_after_check_in

  def num_of_days
    (check_out - check_in).to_i
  end

  def total_amount
    total_amount = 0
    if check_in and check_out
      total_amount = num_of_days * price
    end
    total_amount
  end

  def unavailable_dates
    Reservation.pluck(:check_in, :check_out).map do |range|
      { from: range[0], to: range[1] }
    end
  end

  def cancelled?
    self.status == status["Cancelled"]
  end

  def checked_in?
    self.status == status["Checked in"]
  end

  def checked_out?
    self.status == status["Checked out"]
  end

  def charge!(pay_type_params)
    payment_details = {}
    payment_method = nil

    case pay_type
    when "iDeal"
      payment_method = :ideal
      payment_details[:routing] = pay_type_params["routing_number"]
      payment_details[:account] = pay_type_params["account_number"]
    when "Bank Card"
      payment_method = :bank_card
      month, year = pay_type_params["expiration_date"].split(//)
      payment_details[:cc_num] = pay_type_params["credit_card_number"]
      payment_details[:expiration_month] = month
      payment_details[:expiration_year] = year
    when "Pay at stay"
      payment_method = :cash
      payment_details[:confirmation] = pay_type_params["confirmation"]
    end

    payment_result = Paygo.make_payment(
      order_id: id,
      payment_method: payment_method,
      payment_details: payment_details,
    )

    if payment_result.succeeded?
      # ReservationMailer.payment_status(self, true).deliver_later
      puts "SUCCESS"
      self.status = status["Booked - Paid"] if pay_type != "Pay at stay"
    else
      # ReservationMailer.payment_status(self, false).deliver_later
      puts "FAILURE"
      self.status = status["Booked - Payment pending"]
    end
  end

  private

  def check_out_after_check_in
    return if check_out.blank? || check_in.blank?

    if check_out < check_in
      errors.add(:check_out, "must be after the start date")
    end
 end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]
  before_action :set_stay, only: %i[ new create ]
  before_action :set_stay_reserved, only: %i[ show edit ]

  before_action :authenticate_user!, only: %i[ edit update ]

  # GET /reservations or /reservations.json
  def index
    if params[:email] && !params[:email].strip.empty?
      @reservations = Reservation.where(email: params[:email]).eager_load(:stay)
      if @reservations.empty?
        redirect_to root_path, notice: "Could not find any reservations with email: #{params[:email]}"
      end
      session[:email] = params[:email]
      @stays = @reservations.map { |r| r.stay }.pluck(:id, :name).to_h
    else
      if user_signed_in?
        @reservations = Reservation.all.eager_load(:stay)
        @stays = @reservations.map { |r| r.stay }.pluck(:id, :name).to_h
      else
        redirect_to root_path, notice: "Email not provided, please try again"
      end
    end
  end

  # GET /reservations/1 or /reservations/1.json
  def show
    if !user_signed_in?
      if !session[:email] || session[:email] != @reservation.email
        redirect_to root_path
      end
    end
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
    if @reservation.cancelled?
      redirect_to @reservation, notice: "Reservation is cancelled. Further modifications not allowed."
    end
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.stay_id = @stay.id
    @reservation.price = @stay.price
    @reservation.status = @reservation.pay_type == "Pay at stay" ? 0 : 1

    session[:email] = reservation_params[:email]

    respond_to do |format|
      if @reservation.save
        # begin
        #   ChargeOrderJob.perform_async(@reservation.id, pay_type_params.to_h.to_h)
        # rescue RedisClient::CannotConnectError
        #   {}
        # end
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, stay: @stay, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    if Reservation.statuses[params["reservation"]["status"]] < Reservation.statuses[@reservation.status]
      redirect_to @reservation, notice: "Invalid status update"
      return
    end

    if @reservation.checked_in? || @reservation.checked_out?
      redirect_to @reservation, notice: "Cannot update a checked in/out reservation"
      return
    end

    respond_to do |format|
      if @reservation.update(reserved_reservation_params)
        format.html { redirect_to reservation_url(@reservation), stay: @stay, notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, stay: @stay, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    if !user_signed_in?
      if !session[:email] || session[:email] != @reservation.email
        redirect_to root_path
        return
      end
    end

    if @reservation.checked_in? || @reservation.checked_out?
      redirect_to @reservation, notice: "#{user_signed_in? ? "Customer has" : "You have"} already checked in. This reservation cannot be cancelled"
      return
    end

    @reservation.status = Reservation.statuses["Cancelled"]
    respond_to do |format|
      if @reservation.save!
        format.html { redirect_to reservation_url(@reservation), stay: @stay, notice: "Reservation was successfully cancelled." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { redirect_to reservation_url(@reservation), stay: @stay, notice: "An error occurred trying to cancel the reservation." }
        format.json { render :show, status: :internal_server_error, location: @reservation }
      end
    end
  end

  def pay_type_params
    if reservation_params[:pay_type] == "Bank Card"
      params.require(:reservation).permit(:credit_card_number, :expiration_date)
    elsif reservation_params[:pay_type] == "iDeal"
      params.require(:reservation).permit(:routing_number, :account_number)
    elsif reservation_params[:pay_type] == "Pay at stay"
      params.require(:reservation).permit(:confirmation)
    else
      {}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, notice: "Reservation not found"
    end

    def set_stay
      begin
        if params[:stay_id]
          @stay = Stay.find(params[:stay_id])
          if !@stay.enabled?
            redirect_to root_path, notice: "Stay is currently not accepting any reservations"
            return
          end
        else
          redirect_to root_path, notice: "Please select a stay to create a reservation"
          return
        end
      rescue ActiveRecord::RecordNotFound
        redirect_to root_path, notice: "Invalid stay selected"
      end
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:stay_id, :name, :email, :address, :check_in, :check_out, :pay_type)
    end

    def reserved_reservation_params
      params.require(:reservation).permit(:status)
    end

    def set_stay_reserved
      @stay = Stay.find(@reservation.stay_id)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_card.html.erb
<fieldset data-payment-target="additionalFields" data-type="Bank Card">
  <div class="my-5">
    <%= form.label :credit_card_number %>
    <%= form.password_field :credit_card_number, class: "input-field" %>
  </div>
  <div class="my-5">
    <%= form.label :expiration_date %>
    <%= form.text_field :expiration_date, class: "input-field",
 	      size:9, placeholder: "e.g. 03/22" %>
  </div>
</fieldset>

app/views/reservations/_edit_form.html.erb
<%= form_with(model: reservation, class: "contents") do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.select :status, Reservation.statuses.keys, class: "input-field" %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, class: "contents") do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= hidden_field_tag :stay_id, @stay.id %>
  </div>
  
  <div class="my-5 block">
    <%= form.label :name, "Enter your name", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  
  <div class="my-5 block">
    <%= form.label :email, "Enter your email", class: "form-label" %>
    <%= form.email_field :email, class: "form-control" %>
  </div>

  <div class="my-5">
    <%= form.label :address, "Enter your address", class: "form-label" %>
    <%= form.text_area :address, rows: 4, class: "form-control" %>
  </div>

  <div class="my-5">
    <%= form.label :check_in, class: "form-label" %>
    <%= form.date_field :check_in, min: Date.today, value: params[:check_in], class: "form-control" %>
  </div>

  <div class="my-5">
    <%= form.label :check_out, class: "form-label" %>
    <%= form.date_field :check_out, min: Date.tomorrow, value: params[:check_out], class: "form-control" %>
  </div>

  <div data-controller="payment">
    <div class="my-5">
      <%= form.label :pay_type, class: "form-label" %>
      <%= form.select :pay_type, Reservation.pay_types.keys,
 	                      { prompt: 'Select a payment method' },
	                      'data-payment-target' => 'selection',
	                      'data-action' => 'payment#showAdditionalFields',
 	                      class: "form-control" %>
    </div>
    <%= render partial: 'ideal', locals: {form: form} %>
    <%= render partial: 'card', locals: {form: form} %>
    <%= render partial: 'ps', locals: {form: form} %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reservations/_ideal.erb
<fieldset data-payment-target="additionalFields" data-type="iDeal">
  <div class="my-5">
    <%= form.label :routing_number %>
    <%= form.text_field :routing_number, class: "input-field" %>
  </div>
  <div class="my-5">
    <%= form.label :account_number %>
    <%= form.password_field :account_number, class: "input-field" %>
  </div>
</fieldset>

app/views/reservations/_ps.html.erb
<fieldset data-payment-target="additionalFields" data-type="Pay at stay">
  <div class="my-5 block">
    <%= form.check_box :confirmation, class: "input-field" %>
    <%= form.label :confirmation, "I agree to pay the full amount at the stay and understand that I will not be allowed if unpaid" %>
  </div>
</fieldset>

app/views/reservations/_reservation.html.erb
<div id="<%= dom_id reservation %>">
  <table class="table">
    <tr>
      <th>
        <strong class="block font-medium mb-1">Stay:</strong>
      </th>
      <td>
        <% if @stays %>
          <%= @stays[reservation.stay_id] %>
        <% elsif @stay %>
          <%= @stay.name %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        <strong class="block font-medium mb-1">Customer Name:</strong>
      </td>
      <td>
        <%= reservation.name %>
      </td>
    </tr>
    <tr>
      <td>
        <strong class="block font-medium mb-1">Customer Address:</strong>
      </td>
      <td>
        <%= reservation.address %>
      </td>
    </tr>
    <tr>
      <td>
        <strong class="block font-medium mb-1">Customer Email:</strong>
      </td>
      <td>
        <%= reservation.email %>
      </td>
    </tr>
    <tr>
      <td>
        <strong class="block font-medium mb-1">Check in:</strong>
      </td>
      <td>
        <%= reservation.check_in %>
      </td>
    </tr>
    <tr>
      <td>
        <strong class="block font-medium mb-1">Check out:</strong>
      </td>
      <td>
        <%= reservation.check_out %>
      </td>
    </tr>
    <tr>
      <td>
        <strong class="block font-medium mb-1">Amount:</strong>
      </td>
      <td>
        <%= reservation.total_amount %>
      </td>
    </tr>
    <tr>
      <td>
        <strong class="block font-medium mb-1">Status:</strong>
      </td>
      <td>
        <%= reservation.status %>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <%= link_to "Download receipt", generate_receipt_path(reservation), class: "btn btn-primary" %>
      </td>
    </tr>
    </table>
</div>

app/views/reservations/_stay.html.erb
<div id="<%= dom_id stay %>">
  <h1 class="text-center"> <%= stay.name %> </h1>
  <% if !stay.enabled %>
    <h5 class="note note-danger mb-3 text-center"> <%= user_signed_in? ? "This stay is disabled. This will prevent the stay from showing up in search results." : "This stay is curently not taking reservations." %> </h5>
  <% end %>
    <%= image_tag stay.image_url, class: "img-fluid h-50" %>

  <p class="my-5">
    <b class="font-medium mb-1"> Address: </b> <i class="font-medium mb-1"> <%= stay.address %></i>
  </p>

  <div class="grid">

      <p class="my-5">
        <%= stay.description %>
      </p>


    <div class="md:w-2/4 text-right place-items-center">
      <table class="table">
        <tr>
          <td>
            <b class="font-medium mb-1">Max persons: </b>
          </td>
          <td>
            <%= stay.max_persons %>
          </td>
        </tr>

        <tr>
          <td>
            <b class="font-medium mb-1">Pet friendly: </b>
          </td>
          <td>
            <p class="my-2"> <%= stay.pet_friendly ? "Yes" : "No" %> </p>
          </td>
        </tr>

        <tr>
          <td>
              <b class="font-medium mb-1">Bedrooms: </b>
          </td>
          <td>
            <p class="my-2"> <%= stay.bedrooms %> </p>
          </td>
        </tr>

        <tr>
          <td>
              <b class="font-medium mb-1">Bathrooms: </b>
          </td>
          <td>
            <p class="my-2"> <%= stay.bathrooms %> </p>
          </td>
        </tr>

        <tr>
          <td>
              <b class="font-medium mb-1">Area: </b>
          </td>
          <td>
            <p class="my-2"> <%= stay.area %> </p>
          </td>
        </tr>

        <tr>
          <td>
              <strong class="font-medium mb-1">Price per night:</strong>
          </td>
          <td>
            <p class="my-2"> <b> <%= number_to_currency(stay.price, :unit => "€", :separator => ",", :delimiter => ".") %> </p> </b>
          </td>
        </tr>
      </table>

    </div>
  </div>
</div>

app/views/reservations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing reservation</h1>

  <%= render @reservation %>
  <%= render "edit_form", reservation: @reservation %>
</div>

app/views/reservations/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 note note-success text-green-500 font-medium rounded-lg inline-block " id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Reservations" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Reservations</h1>
  </div>

  <%# <div id="reservations" class="min-w-full">
  <%#   <% @reservations.each do |reservation| %>
 <%#      <%= render reservation %>
  <%#     <p>
  <%#       <%= link_to "Show this reservation", reservation, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%#     </p>
  <%#   <% end %>
 <%#  </div> %>

  <table id="reservations" class="mx-auto">
    <tbody>
      <% @reservations.each do |reservation| %>
      <tr class="<%= cycle("bg-green-50", "bg-white") %>">
        <td>
          <h2 class="text-xl font-bold m-2"><%= link_to @stays[reservation.stay_id], reservation, class: "hover:underline" %></h2>
          <p class="m-2"> <b>Customer name:</b> <%= reservation.name %> </p>
          <p class="m-2"> <b>Amount:</b> <%= number_to_currency(reservation.total_amount, :unit => "€", :separator => ",", :delimiter => ".") %> </p>
        </td>
        <td>
          <%= link_to "Show this reservation", reservation, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/reservations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-3xl">Reserving the stay: <%= @stay.name %> </h1>
  <%= render "form", reservation: @reservation %>
  <%= render partial: 'stay', locals: { stay: @stay } %>
  <div class="d-flex justify-content-around gap-10" style="width: 100%">
    <%= link_to "Back to all stays", stays_path(check_in: params[:check_in], check_out: params[:check_out]), class: "btn btn-secondary" %>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 note note-success text-green-500 font-medium rounded-lg inline-block " id="notice"><%= notice %></p>
    <% end %>

    <%= render @reservation %>

    <table class="table">
    <% if !@reservation.cancelled? && !@reservation.checked_out? %>
      <% if user_signed_in? %>
        <tr>
          <td colspan="2">
            <%= link_to "Edit this reservation", edit_reservation_path(@reservation), class: "btn btn-primary" %>
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <%= link_to "Back to reservations", reservations_path, class: "btn btn-secondary" %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td colspan="2">
          <%= button_to "Cancel this reservation", @reservation, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </table>
  </div>
</div>