config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  devise_for :users
  resources :reservations
  resources :stays, only: %i[ index new show edit create update ]

  put "stays/:id/enable", to: "stays#enable", as: "enable_stay"
  put "stays/:id/disable", to: "stays#disable", as: "disable_stay"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "reservations/:id/receipt", to: "generate_receipts#generate_pdf", as: "generate_receipt"
  get "contact", to: "homepage#contact", as: "contact"
  # Defines the root path route ("/")
  root "homepage#index"
end

app/views/layouts/_header.html.erb
    <header class="teal lighten-2">
      <h1><%= @page_title %></h1>
    </header>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary">
  <div class="container-fluid">
    <button
      data-mdb-collapse-init
      class="navbar-toggler"
      type="button"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        <%= link_to image_tag("logo.png", alt: "Reservation Masters Logo", class: "rounded"), root_path %>
      </a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"><%= link_to 'Home', root_path, class: "nav-link" %></li>

        <li><%= link_to 'Contact', contact_path,  class: "nav-link" %></li>
    </ul>


    <div class="d-flex align-items-center">
        <ul class="navbar-nav">
           <% if user_signed_in? %>
            <!--<li class="nav-item">Welcome, <%= current_user.email %></li>-->
            <li class="nav-item"><%= link_to 'See all reservations', reservations_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
          <% else %>
            <li><%= link_to'Admin sign in', new_user_session_path,  class: "nav-link" %></li>
          <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reservation Masters</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Font Awesome -->
  <link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
  />
    <!-- Google Fonts -->
  <link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
  />
    <!-- MDB -->
  <link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.2/mdb.min.css"
  rel="stylesheet"
  />
  </head>
  <body>
    <%= render partial: "layouts/header"%>
    <section class="row">
      <%= render partial: "layouts/navbar"%>
      <main class="container col s10">
        <p class="alert"><%= alert %></p>
        <div class="container w-90 "> 
            <%= yield %>
        </div>
      </main>
    </section>
    <!-- MDB -->
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.2/mdb.umd.min.js"
    ></script>
  </body>
</html>